// <auto-generated />
using System;
using Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BlazorCrudApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240811053653_AddCustomerTable")]
    partial class AddCustomerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCrudApp.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Auth1stBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Auth1stt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Auth2ndAt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Auth2ndBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("AuthStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
