// <auto-generated />
using System;
using Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BlazorCrudApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorCrudApp.Models.Customer", b =>
                {
                    b.Property<string>("Customer_Id")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Auth1stBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Auth1stDt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Auth2ndBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Auth2ndDt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("AuthStatus")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Customer_Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MakeBy")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("MakeDt")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Phone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Customer_Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
